apiVersion: v1
kind: Service
metadata:
  name: matomo
  labels:
    app: matomo
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32222
  selector:
    app: matomo
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: matomo
  labels:
    app: matomo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matomo
  template:
    metadata:
      labels:
        app: matomo
    spec:
      containers:
      - name: matomo
        image: harbor.richinfoai.com/richinfoai/evilless-client:202011060934-07b9a31-v2.6.32-archive
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 0.02
            memory: 32Mi
        env:
        - name: ACTIVE_PROFILE
          valueFrom:
            configMapKeyRef:
              name: const-config
              key: active-profile
        - name: EXTRA_CONFIG
          value: '{"SERVER_NAME":"evilless-client"}'
        - name: WORKER_IP
          valueFrom:
            configMapKeyRef:
              name: const-config
              key: worker-ip
