apiVersion: v1
kind: Service
metadata:
  name: matomo
  labels:
    app: matomo
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32222
  selector:
    app: matomo
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: matomo
  labels:
    app: matomo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matomo
  template:
    metadata:
      labels:
        app: matomo
    spec:
      containers:
      - name: matomo
        image: registry.cn-shanghai.aliyuncs.com/allthink/matomo:3.14.1
        ports:
        - containerPort: 80
        volumeMounts:         # 将存储卷映射到容器内的某路径
        - name: html
          mountPath: /var/www/html
      volumes:              # 这里是选择volume的类型
      - name: matomo-html
        persistentVolumeClaim:
        claimName: mt-pvc
        resources:
          limits:
            cpu: 0.50
            memory: 32Mi
        env:
        - name: ACTIVE_PROFILE
          valueFrom:
            configMapKeyRef:
              name: const-config
              key: active-profile
        - name: EXTRA_CONFIG
          value: '{"SERVER_NAME":"evilless-client"}'
        - name: WORKER_IP
          valueFrom:
            configMapKeyRef:
              name: const-config
              key: worker-ip
