apiVersion: v1
kind: Service
metadata:
  name: matomo
  labels:
    app: matomo
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32222
  selector:
    app: matomo
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: matomo
  labels:
    app: matomo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matomo
  template:
    metadata:
      labels:
        app: matomo
    spec:
      containers:
      - name: matomo
        image: 192.168.51.165:5000/richinfoai/matomo:202011242015-0000000-v3.14.1
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 0.1
            memory: 128Mi
          limits:
            cpu: 2
            memory: 4Gi
        volumeMounts:
        - name: html
          mountPath: /var/www/html
          subPath: matomo
      volumes:
      - name: html
        persistentVolumeClaim:
          claimName: mt-pvc
